version: "3.9"
services:
  web:
    build: .
    ports:
      - "5005:5005"
    environment:
      - CELLXGENE_BUCKET=modulobio-internal-data
      - GATEWAY_LOG_LEVEL=DEBUG
      - CELLXGENE_PREFIX=scrnaseq_datasets/preprocessed/final_all_cells/
    volumes:
      - .:/app/cache
      - ~/.aws:/root/.aws
