version: "3.9"
services:
  web:
    build: .
    ports:
      - "5005:5005"
    environment:
      - CELLXGENE_DATA=/app/data
      - GATEWAY_LOG_LEVEL=INFO
      - GATEWAY_ENABLE_ANNOTATIONS=1
    volumes:
      - .:/app/cache
      - /efs/sequencing_data/scrnaseq_data/cellxgene:/app/data
      - ~/.aws:/root/.aws
